#!/bin/sh

## Open folders in nnn
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube tagesschau scinexx geforcenow steam netflix weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && kitty -e nnn ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && kitty -e nnn ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && kitty -e nnn ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && kitty -e nnn ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && kitty -e nnn ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && kitty -e nnn ~/.local/share &

fi
