#!/bin/sh

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube tagesschau scinexx geforcenow netflix weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty &

elif [[ "$1" == "--gn" ]]; then
	close_dash && chromium --profile-directory=Default --app-id=egmafekfmcnknbdlbfbhafbllplmjlhn &

elif [[ "$1" == "--wa" ]]; then
	close_dash && chromium --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm &

elif [[ "$1" == "--fm" ]]; then
	close_dash && nnn ~ &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--is" ]]; then
	close_dash && inkscape &

fi
