#!/bin/sh

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube tagesschau scinexx geforcenow steam netflix weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--gmail" ]]; then
	close_dash && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--imail" ]]; then
	close_dash && ${cmd} "https://roundcube.inquies.de"

elif [[ "$1" == "--pmail" ]]; then
	close_dash && ${cmd} "https://mail.ovh.net"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"

elif [[ "$1" == "--nf" ]]; then
	close_dash && ${cmd} "https://netflix.com"

elif [[ "$1" == "--ts" ]]; then
	close_dash && ${cmd} "https://tagesschau.de"

elif [[ "$1" == "--sn" ]]; then
	close_dash && ${cmd} "https://scinexx.de"

fi
